name: location_finder
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/beingful/google_maps_lib

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  google_maps_flutter: ^2.7.0
  flutter_map_math: ^0.1.7
  latlong2: ^0.9.1
  
dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
